from Enitites.TypeEnum import InputType
from Enitites.Input import Input
from Enitites.Story import Story
from Enitites.Roman import Roman
from Enitites.Question import Question
from Enitites.Ore import Ore
from Enitites.StoryRoman import StoryRoman
from Enitites.StoryOre import StoryOre
from Enitites.QuestionRoman import QuestionRoman
from Enitites.QuestionOre import QuestionOre
from Enitites.RomanSynonym import RomanSynonym