from GlobeCurrencyCalculator.WorkflowModule.IWorkflow import IWorkflow
from GlobeCurrencyCalculator.WorkflowModule.StoryRomanWf import StoryRomanWf
from GlobeCurrencyCalculator.WorkflowModule.StoryOreWf import StoryOreWf